### PR TITLE
JBIDE-22130: Upgrade FreeMarker to 2.3.24

### PR DESCRIPTION
**Pull request by ddekany**

### CODE REVIEW

**Comment by alexeykazakov** [comment]
Please create an issue in JIRA and add the JIRA number to the commit message and the PR title. Thanks!

**Comment by ddekany** [comment]
Added the issue number

**Comment by ddekany** [comment]
Squashed commits and rebased it on master.

**Comment by ddekany** [comment]
Wait with merging this... the error marker tab offset calculation of the other pull requests somehow doesn't agree with 2.3.24. Strange.

**Comment by ddekany** [comment]
OK, I have added a workaround to the other pull request, so now this can be merged. (2.3.24 has upgraded its JavaCC dependency, which has switched from tab width 8 to tab width 1...)

**Comment by alexeykazakov** [comment]
Rebased and pushed to master. Thanks!

**Pull request closed without merging**
