### PR TITLE
JBIDE-22765: Added missing entries to the list of known FTL directives: setting, nt, compress

### PR DESCRIPTION
**Pull request by ddekany**

### CODE REVIEW

**Comment by alexeykazakov** [comment]
testPR

**Comment by alexeykazakov** [comment]
any tests for this?

**Comment by alexeykazakov** [comment]
Failed tests: 
org.jboss.ide.eclipse.freemarker.editor.coloring.test.AssignColoringTest.testAssignColoring	8.8 sec	1
 org.jboss.ide.eclipse.freemarker.editor.coloring.test.InterpolationColoringTest.testInterpolationColoring	10 sec	1
 org.jboss.ide.eclipse.freemarker.editor.coloring.test.ListColoringTest.testListColoring	10 sec	1
 org.jboss.ide.eclipse.freemarker.editor.coloring.test.PartitionClosingColoringTest.test	10 sec	1
 org.jboss.ide.eclipse.freemarker.editor.coloring.test.PartitionClosingSquColoringTest.test	10 sec	1
 org.jboss.ide.eclipse.freemarker.editor.coloring.test.MultilineColoringTest.testColoring	8.3 sec	1
 org.jboss.ide.eclipse.freemarker.editor.coloring.test.EscapedIdentifiersColoringTest.test

**Comment by ddekany** [comment]
What are the failure details? The "Details" link leads to an invalid domain.  (I did run `mvn clean verify` before the PR and it was successful.)

**Comment by alexeykazakov** [comment]
Error Message

Mismatch at index 6 expected:<StyleRange {19, 1, fontStyle=normal, foreground=Color {4, 4, 4, 255}}> but was:<StyleRange {19, 2, fontStyle=normal, foreground=Color {4, 4, 4, 255}}>
Stacktrace

junit.framework.AssertionFailedError: Mismatch at index 6 expected:<StyleRange {19, 1, fontStyle=normal, foreground=Color {4, 4, 4, 255}}> but was:<StyleRange {19, 2, fontStyle=normal, foreground=Color {4, 4, 4, 255}}>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.TestCase.assertEquals(TestCase.java:244)
	at org.jboss.ide.eclipse.freemarker.editor.coloring.test.AbstractColoringTest.validateColoring(AbstractColoringTest.java:115)
	at org.jboss.ide.eclipse.freemarker.editor.coloring.test.AssignColoringTest.testAssignColoring(AssignColoringTest.java:139)

**Comment by alexeykazakov** [comment]
`Error Message

Mismatch at index 13 expected:<StyleRange {71, 1, fontStyle=normal, foreground=Color {4, 4, 4, 255}}> but was:<StyleRange {71, 2, fontStyle=normal, foreground=Color {4, 4, 4, 255}}>
Stacktrace

junit.framework.AssertionFailedError: Mismatch at index 13 expected:<StyleRange {71, 1, fontStyle=normal, foreground=Color {4, 4, 4, 255}}> but was:<StyleRange {71, 2, fontStyle=normal, foreground=Color {4, 4, 4, 255}}>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.TestCase.assertEquals(TestCase.java:244)
	at org.jboss.ide.eclipse.freemarker.editor.coloring.test.AbstractColoringTest.validateColoring(AbstractColoringTest.java:115)
	at org.jboss.ide.eclipse.freemarker.editor.coloring.test.InterpolationColoringTest.testInterpolationColoring(InterpolationColoringTest.java:146)`

**Comment by alexeykazakov** [comment]
The tests pass locally for me too..

**Comment by ddekany** [comment]
I don't think this PR has caused  the problem, so perhaps somethings was changed on CI server. How's the CI server environment differs from our local environment anyway? Perhaps a test case bug that surfaces depending on timing...

Also, I see "expected: but was:" above, that is, it's not shown what was expected what what we got instead. Some copy-pasting + markdown issue maybe?

**Comment by alexeykazakov** [comment]
See the updated comments above. I fixed the the markdown issue.

**Comment by ddekany** [comment]
Looks like CR vs CR LF issue... will try to look into it in the coming days.

**Comment by ddekany** [comment]
testPR

**Comment by odockal** [comment]
testPR

**Comment by alexeykazakov** [comment]
testPR

**Comment by alexeykazakov** [comment]
Failing integration tests:
```
Error Message

There are no items matching matcher tree item text on position <0> matches "list-directive.ftl"
Stacktrace

org.jboss.reddeer.core.exception.CoreLayerException: There are no items matching matcher tree item text on position <0> matches "list-directive.ftl"
	at org.jboss.reddeer.core.lookup.TreeItemLookup.getTreeItems(TreeItemLookup.java:132)
	at org.jboss.reddeer.core.lookup.TreeItemLookup.getTreeItems(TreeItemLookup.java:84)
	at org.jboss.reddeer.core.lookup.TreeItemLookup.getTreeItem(TreeItemLookup.java:63)
	at org.jboss.reddeer.swt.impl.tree.DefaultTreeItem.<init>(DefaultTreeItem.java:47)
	at org.jboss.reddeer.swt.impl.tree.DefaultTreeItem.<init>(DefaultTreeItem.java:37)
	at org.jboss.tools.freemarker.ui.bot.test.FreemarkerDirectiveTest.openFTLFileInEditor(FreemarkerDirectiveTest.java:124)
	at org.jboss.tools.freemarker.ui.bot.test.FreemarkerDirectiveTest.listDirectiveOutlineTest(FreemarkerDirectiveTest.java:108)

Error Message

There are no items matching matcher tree item text on position <0> matches "macro-def-directive.ftl"
Stacktrace

org.jboss.reddeer.core.exception.CoreLayerException: There are no items matching matcher tree item text on position <0> matches "macro-def-directive.ftl"
	at org.jboss.reddeer.core.lookup.TreeItemLookup.getTreeItems(TreeItemLookup.java:132)
	at org.jboss.reddeer.core.lookup.TreeItemLookup.getTreeItems(TreeItemLookup.java:84)
	at org.jboss.reddeer.core.lookup.TreeItemLookup.getTreeItem(TreeItemLookup.java:63)
	at org.jboss.reddeer.swt.impl.tree.DefaultTreeItem.<init>(DefaultTreeItem.java:47)
	at org.jboss.reddeer.swt.impl.tree.DefaultTreeItem.<init>(DefaultTreeItem.java:37)
	at org.jboss.tools.freemarker.ui.bot.test.FreemarkerDirectiveTest.openFTLFileInEditor(FreemarkerDirectiveTest.java:124)
	at org.jboss.tools.freemarker.ui.bot.test.FreemarkerDirectiveTest.macroDefDirectiveOutlineTest(FreemarkerDirectiveTest.java:78)
```
@odockal could you please take a look?

**Comment by alexeykazakov** [comment]
This is the failing test - https://github.com/jbosstools/jbosstools-integration-tests/blob/725a4de8a1ee8b7110fb9cc6b2dbb129fb71b1c0/tests/org.jboss.tools.freemarker.ui.bot.test/src/org/jboss/tools/freemarker/ui/bot/test/FreemarkerDirectiveTest.java

**Comment by alexeykazakov** [comment]
I merged this PR by accident :(
But anyway this PR seems to be fine but we need to fix the failing integration test above.
@odockal @ddekany

**Comment by ddekany** [comment]
Were the integration tests ran for earlier PR-s too, or it's a new thing? I didn't know that FM plugin tests exist outside `org.jboss.ide.eclipse.freemarker`... I suppose I should check them out and run them next time.

**Comment by alexeykazakov** [comment]
@ddekany previously the integration tests were run separately by QE. We are now integrating them to github checks so we can see if they fail.

**Comment by odockal** [comment]
@alexeykazakov @ddekany These test became unstable recently. Exceptions are caused by hanging content menu and causes these random errors. When I debug tests and close the menu manually, tests are run without errors. Today, I would like to find that cause and remove it.

**Comment by alexeykazakov** [comment]
OK. Thanks @odockal for the update! So, the PR has been merged and I'm resolving JBIDE-22765

**Pull request merged**
